name: Doc Page Publish

on:
  push:
    branches: [docs]
  pull_request:
    branches: [docs]

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: checkout
        uses: actions/checkout@v3

      - name: install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: publish
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: docs
          folder: dist
          target-folder: docs
